"""Dependency-free self-contained HTML reports for guided exploration."""
from __future__ import annotations

import html
from pathlib import Path
from typing import Any


def render_exploration_report(exploration: dict[str, Any]) -> str:
    profile, plan, analysis = exploration["profile"], exploration["plan"], exploration["analysis"]
    best = max(analysis["resolution_runs"], key=lambda run: (run["endpoint_cp_gain"], -run["resolution"]))
    graph = best["result"]
    gains = [(row["resolution"], row["mean_endpoint_cp_gain"]) for row in analysis["per_resolution"]]
    support = graph["state_support"]["observation_counts"]
    macro_tpm = graph["ce2"]["endpoint"]["macro_tpm"]
    states = exploration["state_descriptions"][0]["states"]
    title = Path(profile["source"]["path"]).name
    return f"""<!doctype html><html><head><meta charset='utf-8'><title>CE2 exploration report</title>
<style>{_CSS}</style></head><body><main>
<header><p class='eyebrow'>CAUSAL EMERGENCE EXPLORATION</p><h1>{html.escape(title)}</h1><p>Evidence-linked, model-derived analysis. This report does not independently identify real-world interventions.</p></header>
<section class='grid'>{_card('Rows', profile['row_count'])}{_card('Trajectories', profile['trajectory_count'])}{_card('Profile', analysis['profile']['classification'].replace('_',' '))}{_card('Best CE gain', f"{best['endpoint_cp_gain']:.5f}")}</section>
<section><h2>Analysis plan</h2><p><b>Entity:</b> {html.escape(str(plan['entity_column']))} &nbsp; <b>Time:</b> {html.escape(str(plan['time_column']))}</p><p><b>Features:</b> {html.escape(', '.join(plan['feature_columns']))}</p><p><b>Resolutions:</b> {', '.join(map(str, plan['resolutions']))} &nbsp; <b>Seeds:</b> {', '.join(map(str, plan['encoder_seeds']))}</p></section>
<section class='two'><div><h2>CE by resolution</h2>{_line_chart(gains)}</div><div><h2>State support</h2>{_bar_chart(support)}</div></section>
<section class='two'><div><h2>Selected macro dynamics</h2>{_heatmap(macro_tpm)}</div><div><h2>Selected hierarchy</h2><p>{html.escape(graph['narrative_text'])}</p><dl><dt>Endpoint</dt><dd>{html.escape(best['endpoint_partition_id'])}</dd><dt>Macro states</dt><dd>{best['endpoint_macro_state_count']}</dd><dt>Search</dt><dd>{html.escape(str(graph['search']['mode']))}</dd></dl></div></section>
<section><h2>Learned state descriptions</h2><div class='state-grid'>{''.join(_state_card(state) for state in states)}</div></section>
<section><h2>Validation and limitations</h2>{_validation(graph)}<ul>{''.join(f'<li>{html.escape(item)}</li>' for item in analysis['limitations'])}</ul></section>
<footer>Generated by causal-emergence-zoo · Reproducible parameters are embedded in the companion JSON result.</footer>
</main></body></html>"""


def _card(label: str, value: Any) -> str:
    return f"<div class='card'><span>{html.escape(str(label))}</span><strong>{html.escape(str(value))}</strong></div>"


def _line_chart(points: list[tuple[int, float]]) -> str:
    width, height, pad = 520, 230, 35
    max_y = max([value for _, value in points] + [0.001])
    coords = []
    for index, (_, value) in enumerate(points):
        x = pad + index * ((width - 2 * pad) / max(1, len(points) - 1))
        y = height - pad - value / max_y * (height - 2 * pad)
        coords.append((x, y, value))
    path = ' '.join(f"{x:.1f},{y:.1f}" for x, y, _ in coords)
    labels = ''.join(f"<text x='{x:.1f}' y='{height-10}' text-anchor='middle'>K{points[i][0]}</text><circle cx='{x:.1f}' cy='{y:.1f}' r='5'/><text x='{x:.1f}' y='{y-10:.1f}' text-anchor='middle'>{value:.3f}</text>" for i, (x, y, value) in enumerate(coords))
    return f"<svg viewBox='0 0 {width} {height}' role='img'><line x1='{pad}' y1='{height-pad}' x2='{width-pad}' y2='{height-pad}'/><polyline points='{path}'/>{labels}</svg>"


def _bar_chart(values: list[int]) -> str:
    width, height, pad = 520, 230, 30
    maximum = max(values + [1]); bar = (width - 2 * pad) / len(values)
    shapes = ''.join(f"<rect x='{pad+i*bar+4:.1f}' y='{height-pad-v/maximum*(height-2*pad):.1f}' width='{bar-8:.1f}' height='{v/maximum*(height-2*pad):.1f}'/><text x='{pad+(i+.5)*bar:.1f}' y='{height-10}' text-anchor='middle'>S{i}</text>" for i, v in enumerate(values))
    return f"<svg viewBox='0 0 {width} {height}' role='img'>{shapes}</svg>"


def _heatmap(matrix: list[list[float]]) -> str:
    size = len(matrix); cell = 44
    cells = []
    for row in range(size):
        for column in range(size):
            value = matrix[row][column]; opacity = 0.08 + 0.92 * value
            cells.append(f"<rect x='{column*cell}' y='{row*cell}' width='{cell}' height='{cell}' style='fill:rgba(32,99,155,{opacity:.3f})'/><text x='{column*cell+cell/2}' y='{row*cell+cell/2+4}' text-anchor='middle'>{value:.2f}</text>")
    dimension = size * cell
    return f"<svg class='heatmap' viewBox='0 0 {dimension} {dimension}' role='img'>{''.join(cells)}</svg>"


def _state_card(state: dict[str, Any]) -> str:
    values = sorted(state["centroid"].items(), key=lambda item: item[0])[:4]
    details = ''.join(f"<li>{html.escape(name)}: {value:.3g}</li>" for name, value in values)
    return f"<article><span>State {state['state_id']}</span><h3>{html.escape(state['label'])}</h3><ul>{details}</ul></article>"


def _validation(graph: dict[str, Any]) -> str:
    predictive = graph["continuous_data"]["predictive_validation"]
    validation = predictive["validation_micro_tpm"]
    null = graph["continuous_data"]["transition_null_validation"]
    validation_text = "not available" if validation["status"] != "defined" else f"mean NLL {validation['mean_negative_log_likelihood']:.4f}"
    null_text = "not requested" if null["status"] == "not_requested" else f"upper-tail p={null['empirical_upper_tail_probability']:.3f}"
    return f"<p><b>Held-out prediction:</b> {html.escape(validation_text)} &nbsp; <b>Transition null:</b> {html.escape(null_text)}</p>"


_CSS = """body{margin:0;background:#f4f1ea;color:#17212b;font:15px/1.55 system-ui,sans-serif}main{max-width:1120px;margin:auto;padding:48px 28px}header{border-bottom:3px solid #17212b;margin-bottom:28px}h1{font:700 44px Georgia,serif;margin:0 0 12px}h2{font:700 25px Georgia,serif}.eyebrow{color:#a34b2b;letter-spacing:.15em;font-weight:700}.grid,.two,.state-grid{display:grid;gap:18px}.grid{grid-template-columns:repeat(4,1fr)}.two{grid-template-columns:1fr 1fr}.state-grid{grid-template-columns:repeat(3,1fr)}section{background:#fff;padding:24px;margin:18px 0;border:1px solid #d7d1c5}.card span,.state-grid article>span{display:block;color:#68737d;text-transform:uppercase;font-size:12px;letter-spacing:.08em}.card strong{font:700 27px Georgia,serif}.state-grid article{border-left:4px solid #20639b;padding:12px;background:#f7f9fb}.state-grid h3{margin:4px 0}svg{width:100%;max-height:260px}svg line{stroke:#9aa4ad}svg polyline{fill:none;stroke:#a34b2b;stroke-width:4}svg circle,svg rect{fill:#20639b}svg text{font-size:12px;fill:#17212b}.heatmap text{fill:#111;font-size:10px}dt{font-weight:700}footer{color:#68737d;margin-top:30px}@media(max-width:760px){.grid,.two,.state-grid{grid-template-columns:1fr 1fr}}"""
